sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - ls -la /home/travis/.m2/repository/
  - mvn xml:check-format -P xml-check-format
  - mvn formatter:validate -P common-libs
  - mvn -U clean install -P default -X
  - mvn -U jacoco:report coveralls:report -P common-libs
